services:
  central-automacoes-app:
    # Nome do serviço
    container_name: central-automacoes-app
    # Indica que a imagem deve ser construída a partir do Dockerfile no diretório atual:
    build:
      context: .
      dockerfile: Dockerfile
    # Mapeamento de portas: 3003 da máquina host para 3003 do container
    # A porta 3003 é a porta fixa definida para o serviço.
    ports:
      - "3003:3003"
    # Reinicia o container se ele falhar
    restart: always
    # Carrega variáveis de ambiente do arquivo .env (local)
    env_file:
      - .env.local